default:
	@echo publish
	@echo viewRemote


publish:
	scp fernSurvey.nb.html paulshannnon@pshannon.net:public_html/pshannon.net/fernSurvey2025/analysis.html

viewRemote:
	open https://pshannon.net/fernSurvey2025/analysis.html

